-- ================================================================================
-- MASTER DATABASE SCHEMA - FC POPRAD - STRÁŽE
-- ================================================================================

-- 1. ARTICLES (Články)
CREATE TABLE IF NOT EXISTS public.articles (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    excerpt TEXT,
    content TEXT NOT NULL,
    image TEXT,
    category TEXT NOT NULL,
    author TEXT DEFAULT 'FC Poprad - Stráže',
    tags TEXT[] DEFAULT '{}',
    "readTime" INTEGER DEFAULT 5,
    date DATE DEFAULT CURRENT_DATE,
    is_published BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. VIDEOS (Klubová TV)
CREATE TABLE IF NOT EXISTS public.videos (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    date DATE DEFAULT CURRENT_DATE,
    youtubeid TEXT,
    youtubeurl TEXT NOT NULL,
    thumbnail TEXT,
    category TEXT NOT NULL,
    tags TEXT[] DEFAULT '{}',
    views INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. CONTACT MESSAGES (Kontaktný formulár)
CREATE TABLE IF NOT EXISTS public.contact_messages (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. PLAYERS (Hráči)
CREATE TABLE IF NOT EXISTS public.players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    jersey_number INTEGER,
    position TEXT NOT NULL,
    category TEXT NOT NULL,
    date_of_birth DATE,
    age INTEGER,
    height INTEGER,
    weight INTEGER,
    nationality TEXT DEFAULT 'Slovensko',
    birth_year INTEGER,
    bio TEXT,
    matches_played INTEGER DEFAULT 0,
    goals INTEGER DEFAULT 0,
    assists INTEGER DEFAULT 0,
    yellow_cards INTEGER DEFAULT 0,
    red_cards INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. OFFICIALS (Činovníci - Hybridný model: Fotky v Storage, Texty v kóde)
CREATE TABLE IF NOT EXISTS public.officials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    photo_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. PARTNERS (Sponzori)
CREATE TABLE IF NOT EXISTS public.partners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    logo_url TEXT NOT NULL,
    website_url TEXT,
    category TEXT DEFAULT 'Partner',
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ================================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ================================================================================

ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.videos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.officials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.partners ENABLE ROW LEVEL SECURITY;

-- PUBLIC READ ACCESS (Všetci môžu vidieť)
CREATE POLICY "Public read articles" ON public.articles FOR SELECT USING (is_published = TRUE);
CREATE POLICY "Public read videos" ON public.videos FOR SELECT USING (TRUE);
CREATE POLICY "Public read players" ON public.players FOR SELECT USING (is_active = TRUE);
CREATE POLICY "Public read officials" ON public.officials FOR SELECT USING (TRUE);
CREATE POLICY "Public read partners" ON public.partners FOR SELECT USING (TRUE);

-- CONTACT FORM (Vkladanie správ)
CREATE POLICY "Public insert contact messages" ON public.contact_messages FOR INSERT WITH CHECK (TRUE);

-- AUTHENTICATED ADMIN ACCESS (Plný prístup pre prihlásených)
CREATE POLICY "Admin full access articles" ON public.articles FOR ALL TO authenticated USING (TRUE);
CREATE POLICY "Admin full access videos" ON public.videos FOR ALL TO authenticated USING (TRUE);
CREATE POLICY "Admin full access contact_messages" ON public.contact_messages FOR ALL TO authenticated USING (TRUE);
CREATE POLICY "Admin full access players" ON public.players FOR ALL TO authenticated USING (TRUE);
CREATE POLICY "Admin full access officials" ON public.officials FOR ALL TO authenticated USING (TRUE);
CREATE POLICY "Admin full access partners" ON public.partners FOR ALL TO authenticated USING (TRUE);